
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import keeptoo.Drag;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jTextFieldName = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btn_exit = new javax.swing.JLabel();
        kButtonLogin = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kButtonSignup = new keeptoo.KButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jTextFieldMobile = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        kGradientPanel1.setForeground(new java.awt.Color(204, 204, 204));
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                kGradientPanel1MouseDragged(evt);
            }
        });
        kGradientPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kGradientPanel1MousePressed(evt);
            }
        });
        kGradientPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                kGradientPanel1KeyPressed(evt);
            }
        });
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldName.setBackground(new java.awt.Color(0,0,0,0));
        jTextFieldName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldName.setCaretColor(new java.awt.Color(204, 0, 255));
        jTextFieldName.setOpaque(false);
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 350, 32));

        jPasswordField1.setBackground(new java.awt.Color(0,0,0,0));
        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField1.setCaretColor(new java.awt.Color(204, 0, 255));
        jPasswordField1.setOpaque(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, 350, 32));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Re Password");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        btn_exit.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(204, 204, 204));
        btn_exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_xbox_x_50px.png"))); // NOI18N
        btn_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_exitMouseClicked(evt);
            }
        });
        kGradientPanel1.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, 50, 60));

        kButtonLogin.setText("Back");
        kButtonLogin.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        kButtonLogin.setkBorderRadius(40);
        kButtonLogin.setkEndColor(new java.awt.Color(0, 204, 204));
        kButtonLogin.setkFillButton(false);
        kButtonLogin.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        kButtonLogin.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        kButtonLogin.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButtonLogin.setkStartColor(new java.awt.Color(255, 255, 255));
        kButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonLoginMouseClicked(evt);
            }
        });
        kButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonLoginActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 580, 150, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Mobile");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8_add_user_male_100px.png"))); // NOI18N
        jLabel2.setIconTextGap(10);
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 100, 100));

        kButtonSignup.setText("Sign Up");
        kButtonSignup.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        kButtonSignup.setkBorderRadius(40);
        kButtonSignup.setkEndColor(new java.awt.Color(0, 204, 204));
        kButtonSignup.setkFillButton(false);
        kButtonSignup.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        kButtonSignup.setkHoverForeGround(new java.awt.Color(255, 204, 255));
        kButtonSignup.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        kButtonSignup.setkStartColor(new java.awt.Color(255, 255, 255));
        kButtonSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButtonSignupMouseClicked(evt);
            }
        });
        kButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonSignupActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kButtonSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 150, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText(":");
        kGradientPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 90, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Username");
        kGradientPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        jTextFieldUser.setBackground(new java.awt.Color(0,0,0,0));
        jTextFieldUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldUser.setCaretColor(new java.awt.Color(204, 0, 255));
        jTextFieldUser.setOpaque(false);
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 350, 32));

        jTextFieldMobile.setBackground(new java.awt.Color(0,0,0,0));
        jTextFieldMobile.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextFieldMobile.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldMobile.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jTextFieldMobile.setCaretColor(new java.awt.Color(204, 0, 255));
        jTextFieldMobile.setOpaque(false);
        jTextFieldMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMobileActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jTextFieldMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 350, 32));

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Password");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, -1));

        jPasswordField2.setBackground(new java.awt.Color(0,0,0,0));
        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPasswordField2.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        jPasswordField2.setCaretColor(new java.awt.Color(204, 0, 255));
        jPasswordField2.setOpaque(false);
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, 350, 32));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Name");
        kGradientPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText(":");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 90, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText(":");
        kGradientPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 90, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText(":");
        kGradientPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 90, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText(":");
        kGradientPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, 90, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void btn_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_exitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_exitMouseClicked

    private void kButtonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonLoginMouseClicked
        // TODO add your handling code here:
        Login rgf = new Login();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_kButtonLoginMouseClicked

    private void kButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButtonLoginActionPerformed

    private void kButtonSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButtonSignupMouseClicked
        // TODO add your handling code here:
        String name = jTextFieldName.getText();
        String uname = jTextFieldUser.getText();
        String pass = String.valueOf(jPasswordField1.getPassword());
        String re_pass = String.valueOf(jPasswordField2.getPassword());
        String address = jTextFieldMobile.getText();
        if(uname.equals(""))
        {
             JOptionPane.showMessageDialog(null, "Add A Username");
        }
                
        else if(pass.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Add A Password");
        }
        else if(!pass.equals(re_pass))
        {
            JOptionPane.showMessageDialog(null, "Retype The Password Again");
        }
                    
        else if(checkUsername(uname))
        {
            JOptionPane.showMessageDialog(null, "This Username Already Exist");
        }
        else if(checkMobile(address)){
            JOptionPane.showMessageDialog(null, "Enter Your Mobile no Again");
        }
        else{
            PreparedStatement ps;
            String query = "INSERT INTO `the_app_users`(`u_fname`,  `u_uname`, `u_pass`, `u_address`) VALUES (?,?,?,?)";
            try{
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, name);
                //ps.setString(2, lname);
                ps.setString(2, uname);
                ps.setString(3, pass);
                ps.setString(4, address);
                if(ps.executeUpdate() > 0)
               {
                    JOptionPane.showMessageDialog(null, "Registration Success");
                }

            }catch(Exception e){
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_kButtonSignupMouseClicked

    public static boolean checkMobile(String mobile){
        boolean result = false;
        if((mobile.length()!=10)){
            result = true;
            return result;
        }
        if(!((mobile.charAt(0) == '9') || (mobile.charAt(0) == '8') ||(mobile.charAt(0) == '7') || (mobile.charAt(0) == '6'))){
            result = true;
            return result;
        }

        for(int i = 1 ;i<10;i++){
            if(((mobile.charAt(i) == '9') || (mobile.charAt(i) == '8') ||(mobile.charAt(i) == '7') || (mobile.charAt(i) == '6') || (mobile.charAt(i) == '5') || (mobile.charAt(i) == '4') || (mobile.charAt(i) == '3') || (mobile.charAt(i) == '2') || (mobile.charAt(i) == '1') || (mobile.charAt(i) == '0')))
            {
                result = false;
            }
            else{
                result = true;
                break;

            }
        }
        return result;
    }
                        
    public static boolean checkUsername(String username)
    {
            PreparedStatement ps;
            ResultSet rs;
            boolean checkUser = false;
            String query = "SELECT * FROM `the_app_users` WHERE `u_uname` =?";
            try {
                ps = MyConnection.getConnection().prepareStatement(query);
                ps.setString(1, username);
                
                rs = ps.executeQuery();
                
                if(rs.next())
                {
                    checkUser = true;
                }
            }catch (SQLException ex) {
                ex.printStackTrace();
            }
         return checkUser;
    }
    
    private void kButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButtonSignupActionPerformed

    private void kGradientPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MouseDragged
        // TODO add your handling code here:
        new Drag(kGradientPanel1).moveWindow(evt);
    }//GEN-LAST:event_kGradientPanel1MouseDragged

    private void kGradientPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kGradientPanel1MousePressed
        // TODO add your handling code here:
        new Drag(kGradientPanel1).onPress(evt);
        //Use mouse only
    }//GEN-LAST:event_kGradientPanel1MousePressed

    private void kGradientPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kGradientPanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_kGradientPanel1KeyPressed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jTextFieldMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMobileActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextFieldMobile;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldUser;
    private keeptoo.KButton kButtonLogin;
    private keeptoo.KButton kButtonSignup;
    private keeptoo.KGradientPanel kGradientPanel1;
    // End of variables declaration//GEN-END:variables
}
